apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nodejs-app
  template:
    metadata:
      labels:
        app: my-nodejs-app
    spec:
      containers:
        - name: my-nodejs-container
          image: nelsongeeko/suse-sita-demo:v0.32
          ports:
            - containerPort: 3000
          env:
            - name: IMAGE_SOURCE
              value: "/rancher.png" # Set the image path here
---
apiVersion: v1
kind: Service
metadata:
  name: my-nodejs-service
spec:
  selector:
    app: my-nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort

