apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs-humansettlements
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nodejs-humansettlements
  template:
    metadata:
      labels:
        app: my-nodejs-humansettlements
    spec:
      containers:
        - name: my-nodejs-container
          image: nelsongeeko/suse-sita-humansettlements:0.3
          ports:
            - containerPort: 3000
          env:
            - name: CSS_SOURCE
              value: "style.css" # Set the image path here
---
apiVersion: v1
kind: Service
metadata:
  name: my-nodejs-humansettlements-service
spec:
  selector:
    app: my-nodejs-humansettlements
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort

