# Use an official Node.js runtime as the base image
FROM node:14

# Create and set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install application dependencies
RUN npm install ejs
RUN npm install express
# Copy the rest of the application code to the working directory

COPY . .

# Expose the port that the app will listen on
EXPOSE 3000

# Define the command to run your Node.js application
CMD [ "node", "app.js" ]
