apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs-school
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nodejs-school
  template:
    metadata:
      labels:
        app: my-nodejs-school
    spec:
      containers:
        - name: my-nodejs-container
          image: nelsongeeko/suse-sita-school-demo:0.6
          ports:
            - containerPort: 3000
          env:
            - name: IMAGE_SOURCE
              value: "/images/illustrations/generic-classroom" # Set the image path here
---
apiVersion: v1
kind: Service
metadata:
  name: my-nodejs-school-service
spec:
  selector:
    app: my-nodejs-school
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort

